set(FILE_GROUP_assemble "../../../../pic_8b_asm_func.s")
set(FILE_GROUP_assemblePreprocess "")
set(FILE_GROUP_compile "")
set(FILE_GROUP_link "")
set(BUILD_LIBRARY 0)
set(internal_image_name "c:/Users/hehey/MPLABXProjects/f18854.X/_build_mplab/f18854/default/image_default.elf/default.elf")
set(image_name "default.elf")
set(output_dir "c:/Users/hehey/MPLABXProjects/f18854.X/out/f18854")
