function(assemble_rule target)
    set(inputVar "${MP_CC};-c;${MP_EXTRA_AS_PRE};-mcpu=16F18854;-mdfp=C:/Users/hehey/.mchp_packs/Microchip/PIC16F1xxxx_DFP/1.24.387/xc8;-fno-short-double;-fno-short-float;-memi=wordwrite;-O0;-fasmfile;-maddrqual=ignore;-xassembler-with-cpp;-mwarn=-3;-Wa,-a;-DXPRJ_default=default;-msummary=-psect,-class,+mem,-hex,+file;-Wl,-Pintentry=04h;-ginhx32;-Wl,--no-data-init;-mkeep-startup;-Wl,-nostartfiles;-mno-osccal;-moscval=0x3400;-mno-download;-mno-stackcall;-mdefault-config-bits;-std=c99;-gdwarf-3;-mstack=compiled:auto:auto:auto;${INSTRUMENTED_TRACE_OPTIONS}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(assemblePreprocess_rule target)
    set(inputVar "-c;${MP_EXTRA_AS_PRE};-mcpu=16F18854;-mdfp=C:/Users/hehey/.mchp_packs/Microchip/PIC16F1xxxx_DFP/1.24.387/xc8;-fno-short-double;-fno-short-float;-memi=wordwrite;-O0;-fasmfile;-maddrqual=ignore;-xassembler-with-cpp;-mwarn=-3;-Wa,-a;-DXPRJ_default=default;-msummary=-psect,-class,+mem,-hex,+file;-Wl,-Pintentry=04h;-ginhx32;-Wl,--no-data-init;-mkeep-startup;-Wl,-nostartfiles;-mno-osccal;-moscval=0x3400;-mno-download;-mno-stackcall;-mdefault-config-bits;-std=c99;-gdwarf-3;-mstack=compiled:auto:auto:auto;${INSTRUMENTED_TRACE_OPTIONS}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(compile_rule target)
    set(inputVar "${MP_CC};${MP_EXTRA_CC_PRE};-mcpu=16F18854;-c;-mdfp=C:/Users/hehey/.mchp_packs/Microchip/PIC16F1xxxx_DFP/1.24.387/xc8;-fno-short-double;-fno-short-float;-memi=wordwrite;-O0;-fasmfile;-maddrqual=ignore;-xassembler-with-cpp;-mwarn=-3;-Wa,-a;-DXPRJ_default=default;-msummary=-psect,-class,+mem,-hex,+file;-Wl,-Pintentry=04h;-ginhx32;-Wl,--no-data-init;-mkeep-startup;-Wl,-nostartfiles;-mno-osccal;-moscval=0x3400;-mno-download;-mno-stackcall;-mdefault-config-bits;-std=c99;-gdwarf-3;-mstack=compiled:auto:auto:auto;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS}")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_compile_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
function(link_rule target)
    set(inputVar "${MP_EXTRA_LD_PRE};-mcpu=16F18854;-Wl,-Map=mem.map;-DXPRJ_default=default;-Wl,--defsym=__MPLAB_BUILD=1;-mdfp=C:/Users/hehey/.mchp_packs/Microchip/PIC16F1xxxx_DFP/1.24.387/xc8;-fno-short-double;-fno-short-float;-memi=wordwrite;-O0;-fasmfile;-maddrqual=ignore;-xassembler-with-cpp;-mwarn=-3;-Wa,-a;-msummary=-psect,-class,+mem,-hex,+file;-Wl,-Pintentry=04h;-ginhx32;-Wl,--no-data-init;-mkeep-startup;-Wl,-nostartfiles;-mno-osccal;-moscval=0x3400;-mno-download;-mno-stackcall;-mdefault-config-bits;-std=c99;-gdwarf-3;-mstack=compiled:auto:auto:auto;${INSTRUMENTED_TRACE_OPTIONS};${FUNCTION_LEVEL_PROFILING_OPTIONS};-Wl,--memorysummary,memoryfile.xml,")
    string(REGEX REPLACE "[,]+" "," noDoubleCommas "${inputVar}")
    string(REGEX REPLACE ",$" "" noDanglingCommas "${noDoubleCommas}")
    target_link_options(${target} PRIVATE "${noDanglingCommas}")
endfunction()
